# Generated by Django 4.0.6 on 2022-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customusers',
            name='business_name',
            field=models.CharField(default='Rotana hotels and suites', max_length=80, verbose_name='Business Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
