# Generated by Django 4.0.6 on 2022-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='business_name_alias',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Business alias'),
        ),
    ]
