# Generated by Django 4.0.6 on 2023-01-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customusers_business_name_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='business_type',
            field=models.CharField(choices=[('hospitality', 'hospitality'), ('ecommerce', 'ecommerce')], default='hospitality', max_length=12, verbose_name='Business Category'),
            preserve_default=False,
        ),
    ]
