# Generated by Django 4.0.6 on 2023-01-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customusers_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='address',
            field=models.TextField(),
        ),
    ]
