# Generated by Django 4.0.6 on 2023-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customusers_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='subscription',
            field=models.CharField(choices=[('basic', 'basic'), ('superstore', 'superstore'), ('megastore', 'megastore'), ('megadeals', 'megadeals')], default='basic', max_length=10, verbose_name='Ads Subscription'),
        ),
    ]
