# Generated by Django 4.0.6 on 2022-12-10 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='city',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='country',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='contact_of',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='enable',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_adult',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_kids',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(default='We also need to fuck'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='8cab7de5-81f4-4bee-b811-1b496f8b0703', on_delete=django.db.models.deletion.CASCADE, related_name='contact+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
