# Generated by Django 4.0.6 on 2022-12-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_address_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='acsolotltd@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
