# Generated by Django 4.0.6 on 2022-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hero_image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ManyToManyField(blank=True, to='menu.menu')),
                ('room', models.ManyToManyField(blank=True, to='menu.room')),
                ('staff', models.ManyToManyField(blank=True, to='menu.staff')),
            ],
        ),
    ]
