# Generated by Django 4.0.6 on 2022-12-09 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_contact'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Contact',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_contact+', to='menu.contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
