# Generated by Django 4.0.6 on 2022-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='08100482341', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='hotel_contact+', to='menu.contact'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
