# Generated by Django 4.0.6 on 2022-12-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_phone_alter_hotel_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
