# Generated by Django 4.0.6 on 2022-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_contact_hotel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(default='ibmabdulsalam@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
