# Generated by Django 4.0.6 on 2022-12-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_staff_options'),
        ('hotel', '0003_rename_contact_hotel_contact_hotel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_contact+', to='menu.contact'),
        ),
    ]
