# Generated by Django 4.0.6 on 2022-12-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_staff_options'),
        ('hotel', '0004_alter_hotel_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact',
            field=models.ManyToManyField(related_name='hotel_contact+', to='menu.contact'),
        ),
    ]
