# Generated by Django 4.0.6 on 2022-12-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_about'),
        ('hotel', '0004_remove_hotel_address_remove_hotel_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='about',
        ),
        migrations.AddField(
            model_name='hotel',
            name='about',
            field=models.ManyToManyField(blank=True, to='menu.about'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='hero'),
        ),
    ]
