# Generated by Django 4.0.6 on 2022-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_page_remove_contact_enable_remove_menu_enable_and_more'),
        ('hotel', '0005_remove_hotel_contact_hotel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='page',
            field=models.ManyToManyField(blank=True, to='menu.page'),
        ),
    ]
