# Generated by Django 4.0.6 on 2022-12-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_about'),
        ('hotel', '0005_remove_hotel_about_hotel_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='about',
        ),
        migrations.AddField(
            model_name='hotel',
            name='about',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='about+', to='menu.about'),
            preserve_default=False,
        ),
    ]
