# Generated by Django 4.0.6 on 2022-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_page_background'),
        ('hotel', '0006_remove_hotel_about_hotel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.ManyToManyField(blank=True, to='menu.review'),
        ),
    ]
