# Generated by Django 4.0.6 on 2022-12-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_visitlog_visited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='visited_on',
        ),
    ]
