# Generated by Django 4.0.6 on 2022-12-31 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_remove_visitlog_visited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='visited_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
