# Generated by Django 4.0.6 on 2023-01-03 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_page_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_genproduct'),
        ('hotel', '0012_visitlog_visited_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, upload_to='hero')),
                ('about', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='about+', to='menu.about')),
                ('contact', models.ManyToManyField(blank=True, related_name='hotel_contact+', to='menu.contact')),
                ('page', models.ManyToManyField(blank=True, to='menu.page')),
                ('products', models.ManyToManyField(blank=True, to='products.genproduct')),
                ('review', models.ManyToManyField(blank=True, to='menu.review')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
