# Generated by Django 4.0.6 on 2023-01-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_genproduct_images'),
        ('hotel', '0013_ecommerce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, to='products.genproduct'),
        ),
    ]
