# Generated by Django 4.0.6 on 2023-01-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0014_alter_ecommerce_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerce',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecomm+', to=settings.AUTH_USER_MODEL),
        ),
    ]
