# Generated by Django 4.0.6 on 2023-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_ecommerce_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerce',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
