# Generated by Django 4.0.6 on 2022-12-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='img',
        ),
    ]
