# Generated by Django 4.0.6 on 2022-12-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('phone', 'phone'), ('social', 'social')], max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
