# Generated by Django 4.0.6 on 2022-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_contact_user_alter_menu_user_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='img',
            field=models.ImageField(blank=True, upload_to='review'),
        ),
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
    ]
