# Generated by Django 4.0.6 on 2022-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_staff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('contact', 'contact'), ('menu', 'menu'), ('review', 'review')], max_length=15)),
                ('subtitle', models.CharField(max_length=128)),
                ('enable', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enable & Disable Page',
                'verbose_name_plural': 'Enable & Disable Pages',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='enable',
        ),
        migrations.RemoveField(
            model_name='room',
            name='enable',
        ),
    ]
