# Generated by Django 4.0.6 on 2022-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_page_title_alter_staff_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, upload_to='background'),
        ),
    ]
