# Generated by Django 4.0.6 on 2022-12-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title_alias',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
