# Generated by Django 4.0.6 on 2022-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_page_title_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nature',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='link',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(choices=[('phone', 'phone'), ('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram'), ('linkedin', 'linkedin'), ('gmail', 'gmail')], max_length=15),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(choices=[('home', 'home'), ('about', 'about'), ('rooms', 'rooms'), ('team', 'team'), ('contact', 'contact'), ('menu', 'menu'), ('review', 'review')], max_length=15),
        ),
    ]
