# Generated by Django 4.0.6 on 2022-12-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_remove_contact_nature_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.CharField(default='daily', max_length=30),
        ),
    ]
