# Generated by Django 4.0.6 on 2022-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_room_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='background'),
        ),
    ]
