# Generated by Django 4.0.6 on 2023-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_about_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='note',
            field=models.TextField(default='room detail'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Change Name', max_length=30),
        ),
    ]
