# Generated by Django 4.0.6 on 2023-01-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_remove_review_img_alter_room_img_alter_room_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
