# Generated by Django 4.0.6 on 2023-01-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(choices=[('home', 'home'), ('about', 'about'), ('rooms', 'rooms'), ('products', 'products'), ('team', 'team'), ('contact', 'contact'), ('menu', 'menu'), ('review', 'review')], max_length=15),
        ),
    ]
