# Generated by Django 4.0.6 on 2023-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='body',
            field=models.TextField(default='my about sample text should be about 100-150 words', max_length=256),
        ),
    ]
