# Generated by Django 4.0.6 on 2023-01-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_ads_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_category+', to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='thumbs',
            field=models.ManyToManyField(blank=True, related_name='product_thumbs+', to='products.productimages'),
        ),
    ]
