# Generated by Django 4.0.6 on 2023-01-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_remove_productimages_product_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='user',
            field=models.ForeignKey(default='8cab7de5-81f4-4bee-b811-1b496f8b0703', on_delete=django.db.models.deletion.CASCADE, related_name='product_user+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
