# Generated by Django 4.0.6 on 2023-01-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_views_productimages_projection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbs',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='user',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productimg+', to='products.product'),
            preserve_default=False,
        ),
    ]
