# Generated by Django 4.0.6 on 2023-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_genproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
