# Generated by Django 4.0.6 on 2023-01-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimages_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genproduct',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.productimages'),
        ),
    ]
