# Generated by Django 4.0.6 on 2023-01-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_genproduct_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genproduct',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='gen_images+', to='products.productimages'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='desc',
            field=models.TextField(default='short description'),
        ),
    ]
