# Generated by Django 4.0.6 on 2023-01-05 10:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_genproduct_images_alter_productimages_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=products.models.prod_loc),
        ),
    ]
